import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import DefaultValues from "@/components/default-values/DefaultValues";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <DefaultValues />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
